declare const enum Permission {
    ADMIN = 'ADMIN',
    INSTALLATION_VIEW = 'INSTALLATION:VIEW',
    INSTALLATION_EDIT = "INSTALLATION:EDIT",
    USER_VIEW = "USER:VIEW",
    USER_EDIT = "USER:EDIT",
    CITIZEN_VIEW = "CITIZEN:VIEW",
    CITIZEN_EDIT = "CITIZEN:EDIT",
    JOURNAL_VIEW = "JOURNAL:VIEW",
    JOURNAL_EDIT = "JOURNAL:EDIT",
    MEDICINE_VIEW = "MEDICINE:VIEW",
    MEDICINE_EDIT = "MEDICINE:EDIT",
}
